[global]
developmentMode = false

[server]
runOnSave = false
port = 8501
address = "0.0.0.0"
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"
serverPort = 8501

[theme]
primaryColor = "#667eea"
backgroundColor = "#1e1e2e"
secondaryBackgroundColor = "#2d2d44"
textColor = "#ffffff"
